name: Deployment to NPM
on: 
  push:
    tags:
      - "2.*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: publish
    steps: 
      - name: Publish to NPM
        run: |
          npm build
          npm publish