name: Build Workflow
on: [push, pull_request]

env:
  EAI_USERNAME: ${{secrets.EAI_USERNAME}}
  EAI_PASSWORD: ${{secrets.EAI_PASSWORD}}

jobs:
  PR:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: NPM Build
        run: npm install & npm build 
      - name: Linter
        run: npm run lint
      - name: Unit testing
        run: npm run test:unit
      - name: Integration testing
        run: npm run test:integration

